name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate JKS Keystore
        run: |
          keytool -genkey -v \
            -keystore upload-keystore.jks \
            -alias upload-key \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=ZWL Lokator, OU=Mobile, O=Indiana, L=Warsaw, S=Mazovia, C=PL" \
            -storepass LeoAmidala2026 \
            -keypass LeoAmidala2026
            
      - name: Upload Keystore as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: upload-keystore
          path: upload-keystore.jks
